# these jobs are triggered when the variable run_automated_tests is 'true'

jobs:
- template: build_tools/azure/pytest.yml
  parameters:
    name: pytest_ubuntu
    vmImage: 'ubuntu-16.04'

# these jobs are triggered when the variable build_and_test_wheel is 'true'

- template: build_tools/azure/build_and_test_wheel.yml
  parameters:
    name: build_and_test_wheel
    vmImage: 'macOS-10.14'
    build_docs: 'true'
    is_windows: 'false'
