# these jobs are triggered automatically and they test the code and the examples.

jobs:
- template: build_tools/azure/test_job.yml
  parameters:
    name: test_ubuntu1604
    vmImage: 'ubuntu-16.04'

- template: build_tools/azure/test_job.yml
  parameters:
    name: test_macOS1014
    vmImage: 'macOS-10.14'

- template: build_tools/azure/test_job.yml
  parameters:
    name: test_win2016
    vmImage: 'vs2017-win2016'

# these jobs are triggered manually and they test the code
# and the examples and build the wheels and docs.


- job: 'manylinux2010'
  condition: eq(variables['build_and_test_wheels'], 'true')
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '36'
        python.version: '3.6'
      Python37:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '37'
        python.version: '3.7'

  steps:
  - template: build_tools/azure/steps/prepare_tests.yml
  - template: build_tools/azure/steps/run_pytest.yml
  - script: python setup.py sdist bdist_wheel
    displayName: 'build the wheels'
  - template: build_tools/azure/steps/test_wheels.yml
  - template: build_tools/azure/steps/publish_artifact.yml

    
- template: build_tools/azure/build_wheel_job.yml
  parameters:
    name: macOS1014
    vmImage: 'macOS-10.14'
    build_docs: 'true'


- job: 'win2016'
  condition: eq(variables['build_and_test_wheels'], 'true')
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - template: build_tools/azure/steps/prepare_tests.yml
  - template: build_tools/azure/steps/run_pytest.yml
  - bash: |
      sed -i $'s/\r$//' README.rst
      python setup.py sdist bdist_wheel
    displayName: 'build the wheels'
  - template: build_tools/azure/steps/test_wheels.yml
  - template: build_tools/azure/steps/publish_artifact.yml
