parameters:
  name: ''
  vmImage: ''
  build_docs: 'false'

jobs:
- job: ${{ parameters.name }}
  condition: eq(variables['build_and_test_wheels'], 'true')
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - template: steps/prepare_tests.yml
  - template: steps/run_pytest.yml
  - script: python setup.py sdist bdist_wheel
    displayName: 'build the wheels'
  - template: steps/test_wheels.yml
  - template: steps/build_docs.yml
    parameters:
      build_docs: ${{ parameters.build_docs }}
  - template: steps/publish_artifact.yml
#    condition: succeededOrFailed()
