parameters:
  name: ''
  vmImage: ''
  build_docs: 'false'
  is_windows: 'false'

jobs:
- job: ${{ parameters.name }}
  condition: eq(variables['build_and_test_wheels'], 'true')
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - template: steps/prepare_tests.yml
  - template: steps/run_pytest.yml
  - template: steps/build_wheels.yml
    parameters:
      is_windows: ${{ parameters.is_windows }}
  - template: steps/install_wheels.yml
  - template: steps/test_wheels.yml
  - template: steps/build_docs.yml
    parameters:
      build_docs: ${{ parameters.build_docs }}
  - template: steps/publish_artifact.yml
